### ISSUE TITLE
Request to support multiple accounts

### ISSUE THREAD

**Issue by spainala** [aws-solutions/media-services-application-mapper#160] opened 2020-10-13 18:04 UTC
Please consider adding the ability for MSAM to catalog and visualize more than a single AWS account.

**Comment by JimTharioAmazon** [comment] 2020-10-13 18:06
Duplicate of #5

**Comment by raulmlamzn** [comment] 2023-07-27 16:53
Issue is duplicate of https://github.com/aws-solutions/media-services-application-mapper/issues/5

**Closed** 2023-07-27 16:52 UTC
